export enum Recurso {
	NOTIFICATION_VIEW = 'NOTIFICATION_VIEW',
	NOTIFICATION_CREATE = 'NOTIFICATION_CREATE',
	NOTIFICATION_UPDATE = 'NOTIFICATION_UPDATE',
	NOTIFICATION_REMOVE = 'NOTIFICATION_REMOVE',
}
